export const gameL10n = {
  "English": {
    "Menu": "Menu",
    "Player count": "Player count",
    "Layout": "Layout",
    "Touch mode": "Touch mode",
    "Touch mouse mode": "Touch/mouse mode",
    "Enable": "Enable",
    "Disable": "Disable",
    "Load": "Load",
    "Load quest": "Load quest",
    "Load campaign cards": "Load campaign cards",
    "Load deck (OCTGN file)": "Load deck (OCTGN file)",
    "Load deck (RingsDB URL)": "Load deck (RingsDB URL)",
    "Load game (.json)": "Load game (.json)",
    "Load custom cards (.txt)": "Load custom cards (.txt)",
    "Unload": "Unload",
    "Unload my deck": "Unload my deck",
    "Unload encounter": "Unload encounter",
    "Spawn card": "Spawn card",
    "From the card pool": "From the card pool",
    "Create your own card": "Create your own card",
    "Random": "Random",
    "Coin": "Coin",
    "Number": "Number",
    "Options": "Options",
    "Adjust card size": "Adjust card size",
    "Cards per round": "Cards per round",
    "Battle quest": "Battle quest",
    "Siege quest": "Siege quest",
    "Normal quest": "Normal quest",
    "Special functions": "Special functions",
    "To Catch an Orc Setup": "To Catch an Orc Setup",
    "Escape from Mount Gram Seteup": "Escape from Mount Gram Seteup",
    "The Fortress of Nurn Setup": "The Fortress of Nurn Setup",
    "Glittering Caves Clues": "Glittering Caves Clues",
    "Download": "Download",
    "Game state (.json)": "Game state (.json)",
    "Export cards (.txt)": "Export cards (.txt)",
    "Reload decks": "Reload decks",
    "Clear table": "Clear table",
    "Close room": "Close room",
    "Mark as victory": "Mark as victory",
    "Mark as defeat": "Mark as defeat",
    "Mark as incomplete": "Mark as incomplete",
    "View": "View",
    "Hotkeys": "Hotkeys",
    "Spectators": "Spectators",
    "Quest Companion": "Quest Companion",
    "Shared": "Shared",
    "Player 1": "Player 1",
    "Player 2": "Player 2",
    "Player 3": "Player 3",
    "Player 4": "Player 4",
    "player1": "player1",
    "player2": "player2",
    "player3": "player3",
    "player4": "player4",
    "Encounter Deck": "Encounter Deck", 
    "Encounter Discard": "Encounter Discard", 
    "Discard": "Discard",
    "Quest Deck": "Quest Deck",
    "Quest Discard": "Quest Discard",
    "Second Quest Deck": "Second Quest Deck", 
    "Quest Deck 2": "Quest Deck 2",
    "Second Quest Discard": "Second Quest Discard", 
    "Quest Discard 2": "Quest Discard 2",
    "Second Encounter Deck": "Second Encounter Deck", 
    "Encounter Deck 2": "Encounter Deck 2",
    "Second Encounter Discard": "Second Encounter Discard", 
    "Encounter Discard 2": "Encounter Discard 2",
    "Third Encounter Deck": "Third Encounter Deck", 
    "Encounter Deck 3": "Encounter Deck 3",
    "Third Encounter Discard": "Third Encounter Discard", 
    "Encounter Discard 3": "Encounter Discard 3",
    "Other": "Other", 
    "Set Aside": "Set Aside", 
    "Victory Display": "Victory Display", 
    "Staging Area": "Staging Area", 
    "Active Location": "Active Location", 
    "Active": "Active",
    "Main Quest": "Main Quest", 
    "Extra 1": "Extra 1", 
    "Extra 2": "Extra 2", 
    "Extra 3": "Extra 3", 
    "Hand": "Hand",
    "Deck": "Deck",
    "Play Area": "Play Area",
    "Engaged": "Engaged",
    "Player 1 Hand": "Player 1 Hand", 
    "Player 1 Deck": "Player 1 Deck", 
    "Player 1 Discard": "Player 1 Discard", 
    "Player 1 Sideboard": "Player 1 Sideboard", 
    "Player 1 Deck 2": "Player 1 Deck 2", 
    "Player 1 Play Area 1": "Player 1 Play Area 1",
    "Player 1 Play Area 2": "Player 1 Play Area 2", 
    "Player 1 Play Area 3": "Player 1 Play Area 3", 
    "Player 1 Play Area 4": "Player 1 Play Area 4", 
    "Player 1 Engaged Area": "Player 1 Engaged Area", 
    "Player 1 Current Event": "Player 1 Current Event", 
    "Player 2 Hand": "Player 2 Hand", 
    "Player 2 Deck": "Player 2 Deck", 
    "Player 2 Discard": "Player 2 Discard", 
    "Player 2 Sideboard": "Player 2 Sideboard", 
    "Player 2 Deck 2": "Player 2 Deck 2", 
    "Player 2 Play Area 1": "Player 2 Play Area 1",
    "Player 2 Play Area 2": "Player 2 Play Area 2", 
    "Player 2 Play Area 3": "Player 2 Play Area 3", 
    "Player 2 Play Area 4": "Player 2 Play Area 4", 
    "Player 2 Engaged Area": "Player 2 Engaged Area", 
    "Player 2 Current Event": "Player 2 Current Event", 
    "Player 3 Hand": "Player 3 Hand", 
    "Player 3 Deck": "Player 3 Deck", 
    "Player 3 Discard": "Player 3 Discard", 
    "Player 3 Sideboard": "Player 3 Sideboard", 
    "Player 3 Deck 2": "Player 3 Deck 2", 
    "Player 3 Play Area 1": "Player 3 Play Area 1",
    "Player 3 Play Area 2": "Player 3 Play Area 2", 
    "Player 3 Play Area 3": "Player 3 Play Area 3", 
    "Player 3 Play Area 4": "Player 3 Play Area 4", 
    "Player 3 Engaged Area": "Player 3 Engaged Area", 
    "Player 3 Current Event": "Player 3 Current Event", 
    "Player 4 Hand": "Player 4 Hand", 
    "Player 4 Deck": "Player 4 Deck", 
    "Player 4 Discard": "Player 4 Discard", 
    "Player 4 Sideboard": "Player 4 Sideboard", 
    "Player 4 Deck 2": "Player 4 Deck 2", 
    "Player 4 Play Area 1": "Player 4 Play Area 1",
    "Player 4 Play Area 2": "Player 4 Play Area 2", 
    "Player 4 Play Area 3": "Player 4 Play Area 3", 
    "Player 4 Play Area 4": "Player 4 Play Area 4", 
    "Player 4 Engaged Area": "Player 4 Engaged Area", 
    "Player 4 Current Event": "Player 4 Current Event", 
    "Event": "Event",
    "Round": "Round",
    "Staging": "Staging",
    "Progress": "Progress",
    "Get up": "Get up",
    "Look": "Look",
    "Sit down": "Sit down",
    "Taken": "Taken",
    "Shuffle": "Shuffle",
    "Browse": "Browse",
    "Look at top 5": "Look at top 5",
    "Look at top 10": "Look at top 10",
    "Look at top X": "Look at top X",
    "Choose random": "Choose random",
    "Move to": "Move to",
    "More": "More",
    "Deal top X facedown": "Deal top X facedown",
    "Flip": "Flip",
    "Exhaust": "Exhaust",
    "Prevent refresh": "Prevent refresh",
    "Delete": "Delete",
    "Per round": "Per round",
    "Toggle triggers": "Toggle triggers",
    "Top": "Top",
    "Shuffle in": "Shuffle in",
    "Shuffle into top X": "Shuffle into top X",
    "Shuffle into bottom X": "Shuffle into bottom X",
    "Bottom": "Bottom",
    "New Round": "New Round",
    "Peek": "Peek",
    "Swap with top": "Swap with top",
    "Make visible/hidden": "Make visible/hidden",
    "resource": "Resource",
    "progress": "Progress",
    "damage": "Damage",
    "time": "Time",
    "willpower": "Willpower",
    "attack": "Attack",
    "defense": "Defense",
    "threat": "Threat",
    "hitPoints": "Hit Points",
    "Extra staging areas map": "Extra staging areas / map",
    "Beginning": "Beginning",
    "Resource": "Resource",
    "Set first player": "Set first player",
    "0.0": "Beginning of the round",
    "1.1": "Beginning of the Resource phase",
    "1.R": "1.2 & 1.3: Gain resources and draw cards - <u>then player actions</u>",
    "1.4": "End of the Resource phase",  
    "Planning": "Planning",
    "2.1": "Beginning of the Planning phase",
    "2.P": "2.2 & 2.3: Play cards in turn order - <u>player actions throughout</u>",
    "2.4": "End of the Planning phase",
    "Quest": "Quest",
    "3.1": "Beginning of the Quest phase - <u>then player actions</u>",
    "3.2": "Commit characters to the quest - <u>then player actions</u>",
    "3.3": "Staging - <u>then player actions</u>",
    "3.4": "Quest resolution - <u>then player actions</u>",
    "3.5": "End of the Quest phase",
    "Travel": "Travel",
    "4.1": "Beginning of the Travel phase",
    "4.2": "Travel opportunity - <u>then player actions</u>",
    "4.3": "End of the Travel phase",
    "Encounter": "Encounter",
    "5.1": "Beginning of the Encounter phase",
    "5.2": "Optional engagement - <u>then player actions</u>",
    "5.3": "Engagement checks - <u>then player actions</u>",
    "5.4": "End of the Encounter phase",
    "Combat": "Combat",
    "6.1": "Beginning of the Combat phase",
    "6.2": "Deal shadow cards",
    "6.E": "Enemy attacks - <u>player actions after each combat substep</u>",
    "6.P": "Player attacks - <u>player actions after each combat substep</u>",
    "6.11": "End of the Combat phase",
    "Refresh": "Refresh",
    "7.1": "Beginning of the Refresh phase",
    "7.R": "Ready cards, raise threat, pass P1 token - <u>then player actions</u>",
    "7.5": "End of the Refresh phase",
    "End" : "End"
  },
  "French": {
  },
  "Spanish": {
  }
}