export const gameL10n = {
  "English": {
    "Menu": "Menu",
    "Player count": "Player count",
    "Layout": "Layout",
    "Touch mode": "Touch mode",
    "Touch/mouse mode": "Touch/mouse mode",
    "Enable": "Enable",
    "Disable": "Disable",
    "Load": "Load",
    "Load quest": "Load quest",
    "Load campaign cards": "Load campaign cards",
    "Load deck (OCTGN file)": "Load deck (OCTGN file)",
    "Load deck (RingsDB URL)": "Load deck (RingsDB URL)",
    "Load game (.json)": "Load game (.json)",
    "Load custom cards (.txt)": "Load custom cards (.txt)",
    "Unload": "Unload",
    "Unload my deck": "Unload my deck",
    "Unload encounter": "Unload encounter",
    "Spawn card": "Spawn card",
    "From the card pool": "From the card pool",
    "Create your own card": "Create your own card",
    "Random": "Random",
    "Coin": "Coin",
    "Number": "Number",
    "Options": "Options",
    "Adjust card size": "Adjust card size",
    "Cards per round": "Cards per round",
    "Battle quest": "Battle quest",
    "Siege quest": "Siege quest",
    "Normal quest": "Normal quest",
    "Special functions": "Special functions",
    "To Catch an Orc Setup": "To Catch an Orc Setup",
    "Escape from Mount Gram Seteup": "Escape from Mount Gram Seteup",
    "The Fortress of Nurn Setup": "The Fortress of Nurn Setup",
    "Glittering Caves Clues": "Glittering Caves Clues",
    "Download": "Download",
    "Game state (.json)": "Game state (.json)",
    "Export cards (.txt)": "Export cards (.txt)",
    "Reload decks": "Reload decks",
    "Clear table": "Clear table",
    "Close room": "Close room",
    "Mark as victory": "Mark as victory",
    "Mark as defeat": "Mark as defeat",
    "Mark as incomplete": "Mark as incomplete",
    "View": "View",
    "Hotkeys": "Hotkeys",
    "Spectators": "Spectators",
    "Quest Companion": "Quest Companion",
    "Shared": "Shared",
    "Player 1": "Player 1",
    "Player 2": "Player 2",
    "Player 3": "Player 3",
    "Player 4": "Player 4",
    "player1": "player1",
    "player2": "player2",
    "player3": "player3",
    "player4": "player4",
    "Encounter Deck": "Encounter Deck", 
    "Encounter Discard": "Encounter Discard", 
    "Discard": "Discard",
    "Quest Deck": "Quest Deck",
    "Quest Discard": "Quest Discard",
    "Second Quest Deck": "Second Quest Deck", 
    "Quest Deck 2": "Quest Deck 2",
    "Second Quest Discard": "Second Quest Discard", 
    "Quest Discard 2": "Quest Discard 2",
    "Second Encounter Deck": "Second Encounter Deck", 
    "Encounter Deck 2": "Encounter Deck 2",
    "Second Encounter Discard": "Second Encounter Discard", 
    "Encounter Discard 2": "Encounter Discard 2",
    "Third Encounter Deck": "Third Encounter Deck", 
    "Encounter Deck 3": "Encounter Deck 3",
    "Third Encounter Discard": "Third Encounter Discard", 
    "Encounter Discard 3": "Encounter Discard 3",
    "Other": "Other", 
    "Set Aside": "Set Aside", 
    "Victory Display": "Victory Display", 
    "Staging Area": "Staging Area", 
    "Active Location": "Active Location", 
    "Active": "Active",
    "Main Quest": "Main Quest", 
    "Extra 1": "Extra 1", 
    "Extra 2": "Extra 2", 
    "Extra 3": "Extra 3", 
    "Hand": "Hand",
    "Deck": "Deck",
    "Play Area": "Play Area",
    "Engaged": "Engaged",
    "Player 1 Hand": "Player 1 Hand", 
    "Player 1 Deck": "Player 1 Deck", 
    "Player 1 Discard": "Player 1 Discard", 
    "Player 1 Sideboard": "Player 1 Sideboard", 
    "Player 1 Deck 2": "Player 1 Deck 2", 
    "Player 1 Play Area 1": "Player 1 Play Area 1",
    "Player 1 Play Area 2": "Player 1 Play Area 2", 
    "Player 1 Play Area 3": "Player 1 Play Area 3", 
    "Player 1 Play Area 4": "Player 1 Play Area 4", 
    "Player 1 Engaged Area": "Player 1 Engaged Area", 
    "Player 1 Current Event": "Player 1 Current Event", 
    "Player 2 Hand": "Player 2 Hand", 
    "Player 2 Deck": "Player 2 Deck", 
    "Player 2 Discard": "Player 2 Discard", 
    "Player 2 Sideboard": "Player 2 Sideboard", 
    "Player 2 Deck 2": "Player 2 Deck 2", 
    "Player 2 Play Area 1": "Player 2 Play Area 1",
    "Player 2 Play Area 2": "Player 2 Play Area 2", 
    "Player 2 Play Area 3": "Player 2 Play Area 3", 
    "Player 2 Play Area 4": "Player 2 Play Area 4", 
    "Player 2 Engaged Area": "Player 2 Engaged Area", 
    "Player 2 Current Event": "Player 2 Current Event", 
    "Player 3 Hand": "Player 3 Hand", 
    "Player 3 Deck": "Player 3 Deck", 
    "Player 3 Discard": "Player 3 Discard", 
    "Player 3 Sideboard": "Player 3 Sideboard", 
    "Player 3 Deck 2": "Player 3 Deck 2", 
    "Player 3 Play Area 1": "Player 3 Play Area 1",
    "Player 3 Play Area 2": "Player 3 Play Area 2", 
    "Player 3 Play Area 3": "Player 3 Play Area 3", 
    "Player 3 Play Area 4": "Player 3 Play Area 4", 
    "Player 3 Engaged Area": "Player 3 Engaged Area", 
    "Player 3 Current Event": "Player 3 Current Event", 
    "Player 4 Hand": "Player 4 Hand", 
    "Player 4 Deck": "Player 4 Deck", 
    "Player 4 Discard": "Player 4 Discard", 
    "Player 4 Sideboard": "Player 4 Sideboard", 
    "Player 4 Deck 2": "Player 4 Deck 2", 
    "Player 4 Play Area 1": "Player 4 Play Area 1",
    "Player 4 Play Area 2": "Player 4 Play Area 2", 
    "Player 4 Play Area 3": "Player 4 Play Area 3", 
    "Player 4 Play Area 4": "Player 4 Play Area 4", 
    "Player 4 Engaged Area": "Player 4 Engaged Area", 
    "Player 4 Current Event": "Player 4 Current Event", 
    "Event": "Event",
    "Round": "Round",
    "Staging": "Staging",
    "Progress": "Progress",
    "Get up": "Get up",
    "Look": "Look",
    "Sit down": "Sit down",
    "Taken": "Taken",
    "Shuffle": "Shuffle",
    "Browse": "Browse",
    "Look at top 5": "Look at top 5",
    "Look at top 10": "Look at top 10",
    "Look at top X": "Look at top X",
    "Choose random": "Choose random",
    "Move to": "Move to",
    "More": "More",
    "Deal top X facedown": "Deal top X facedown",
    "Flip": "Flip",
    "Exhaust": "Exhaust",
    "Prevent refresh": "Prevent refresh",
    "Delete": "Delete",
    "Per round": "Per round",
    "Toggle triggers": "Toggle triggers",
    "Top": "Top",
    "Shuffle in": "Shuffle in",
    "Shuffle into top X": "Shuffle into top X",
    "Shuffle into bottom X": "Shuffle into bottom X",
    "Bottom": "Bottom",
    "New Round": "New Round",
    "Peek": "Peek",
    "Swap with top": "Swap with top",
    "Make visible/hidden": "Make visible/hidden",
    "resource": "Resource",
    "progress": "Progress",
    "damage": "Damage",
    "time": "Time",
    "willpower": "Willpower",
    "attack": "Attack",
    "defense": "Defense",
    "threat": "Threat",
    "hitPoints": "Hit Points",
    "Standard": "Standard",
    "Extra staging areas / map": "Extra staging areas / map",
    "Beginning": "Beginning",
    "Resource": "Resource",
    "Set first player": "Set first player",
    "0.0": "Beginning of the round",
    "1.1": "Beginning of the Resource phase",
    "1.R": "1.2 & 1.3: Gain resources and draw cards - <u>then player actions</u>",
    "1.4": "End of the Resource phase",  
    "Planning": "Planning",
    "2.1": "Beginning of the Planning phase",
    "2.P": "2.2 & 2.3: Play cards in turn order - <u>player actions throughout</u>",
    "2.4": "End of the Planning phase",
    "Quest": "Quest",
    "3.1": "Beginning of the Quest phase - <u>then player actions</u>",
    "3.2": "Commit characters to the quest - <u>then player actions</u>",
    "3.3": "Staging - <u>then player actions</u>",
    "3.4": "Quest resolution - <u>then player actions</u>",
    "3.5": "End of the Quest phase",
    "Travel": "Travel",
    "4.1": "Beginning of the Travel phase",
    "4.2": "Travel opportunity - <u>then player actions</u>",
    "4.3": "End of the Travel phase",
    "Encounter": "Encounter",
    "5.1": "Beginning of the Encounter phase",
    "5.2": "Optional engagement - <u>then player actions</u>",
    "5.3": "Engagement checks - <u>then player actions</u>",
    "5.4": "End of the Encounter phase",
    "Combat": "Combat",
    "6.1": "Beginning of the Combat phase",
    "6.2": "Deal shadow cards",
    "6.E": "Enemy attacks - <u>player actions after each combat substep</u>",
    "6.P": "Player attacks - <u>player actions after each combat substep</u>",
    "6.11": "End of the Combat phase",
    "Refresh": "Refresh",
    "7.1": "Beginning of the Refresh phase",
    "7.R": "Ready cards, raise threat, pass P1 token - <u>then player actions</u>",
    "7.5": "End of the Refresh phase",
    "End" : "End",
    "Go Back": "Go back",
    "Detach": "Detach",
    "Swap side": "Swap side",
    "Stop peeking": "Stop peeking",
    "Keep order": "Keep order",
    "Keep peeking": "Keep peeking",
    "Enemy": "Enemy",
    "Location": "Location",
    "Treachery": "Treachery",
    "All": "All",
    "Ally": "Ally",
    "Attachment": "Attachment",
    "Event": "Event",
    "Other": "Other",
    "Easy": "Easy",
    "Normal": "Normal",
    "Nightmare": "Nightmare",
    "None": "None",
    "Top 5": "Top 5",
    "Top 10": "Top 10",
    "Turn faceup...": "Turn faceup...",
    "Close &": "Close &",
  },
  "Spanish": {
    "Menu": "Menú",
    "Player count": "Número de jugadores",
    "Layout": "Formato",
    "Touch mode": "Modo táctil",
    "Touch/mouse mode": "Modo táctil/ratón",
    "Enable": "Habilitar",
    "Disable": "Deshabilitar",
    "Load": "Cargar",
    "Load quest": "Cargar aventura",
    "Load campaign cards": "Cargar cartas de campaña",
    "Load deck (OCTGN file)": "Cargar mazo (archivo de OCTGN)",
    "Load deck (RingsDB URL)": "Cargar mazo (URL de RingsDB)",
    "Load game (.json)": "Cargar partida (.json)",
    "Load custom cards (.txt)": "Cargar cartas no oficiales (.txt)",
    "Unload": "Eliminar",
    "Unload my deck": "Eliminar mi mazo",
    "Unload encounter": "Eliminar mazo de Encuentros",
    "Spawn card": "Generar carta",
    "From the card pool": "Desde el conjunto de cartas",
    "Create your own card": "Crear tu propia carta",
    "Random": "Aleatorio",
    "Coin": "Moneda",
    "Number": "Número",
    "Options": "Opciones",
    "Adjust card size": "Ajustar tamaño de carta",
    "Cards per round": "Cartas por ronda",
    "Battle quest": "Aventura en Batalla",
    "Siege quest": "Aventura en Asedio",
    "Normal quest": "Aventura normal",
    "Special functions": "Funciones especiales",
    "To Catch an Orc Setup": "Preparación de Capturar a un Orco",
    "Escape from Mount Gram Setup": "Preparación de Huida del Monte Gram",
    "The Fortress of Nurn Setup": "Preparación de La Fortaleza de Nurn",
    "Glittering Caves Clues": "Pistas de Las Cavernas Centelleantes",
    "Download": "Descargar",
    "Game state (.json)": "Estado de partida (.json)",
    "Export cards (.txt)": "Exportar cartas (.txt)",
    "Reload decks": "Recargar mazos",
    "Clear table": "Limpiar la mesa",
    "Close room": "Cerrar la sala",
    "Mark as victory": "Marcar como victoria",
    "Mark as defeat": "Marcar como derrota",
    "Mark as incomplete": "Marcar como incompleta",
    "View": "Ver",
    "Hotkeys": "Atajos de teclado",
    "Spectators": "Espectadores",
    "Quest Companion": "Enciclopedia de aventuras",
    "Shared": "Compartido",
    "Player 1": "Jugador 1",
    "Player 2": "Jugador 2",
    "Player 3": "Jugador 3",
    "Player 4": "Jugador 4",
    "player1": "jugador1",
    "player2": "jugador2",
    "player3": "jugador3",
    "player4": "jugador4",
    "Encounter Deck": "Mazo de Encuentros", 
    "Encounter Discard": "Descarte de Encuentros", 
    "Discard": "Descarte",
    "Quest Deck": "Mazo de Misión",
    "Quest Discard": "Descarte de Misión",
    "Second Quest Deck": "Segundo Mazo de Misión", 
    "Quest Deck 2": "Mazo de Misión 2",
    "Second Quest Discard": "Descarte del Segundo Mazo de Misión", 
    "Quest Discard 2": "Descarte de Misión 2",
    "Second Encounter Deck": "Segundo Mazo de Encuentros", 
    "Encounter Deck 2": "Mazo de Encuentros 2",
    "Second Encounter Discard": "Descarte del segundo Mazo de Encuentros", 
    "Encounter Discard 2": "Descarte de Encuentros 2",
    "Third Encounter Deck": "Tercer Mazo de Encuentros", 
    "Encounter Deck 3": "Mazo de Encuentros 3",
    "Third Encounter Discard": "Descarte del tercer Mazo de Encuentros", 
    "Encounter Discard 3": "Descarte de Encuentros 3",
    "Other": "Otro", 
    "Set Aside": "Puesto aparte", 
    "Victory Display": "Zona de Victoria", 
    "Staging Area": "Área de Preparación", 
    "Active Location": "Lugar Activo", 
    "Active": "Activo",
    "Main Quest": "Misión Principal", 
    "Extra 1": "Extra 1", 
    "Extra 2": "Extra 2", 
    "Extra 3": "Extra 3", 
    "Hand": "Mano",
    "Deck": "Mazo",
    "Play Area": "Zona de juego",
    "Engaged": "Enfrentamientos",
    "Player 1 Hand": "Jugador 1 Mano", 
    "Player 1 Deck": "Jugador 1 Mazo", 
    "Player 1 Discard": "Jugador 1 Descartes", 
    "Player 1 Sideboard": "Jugador 1 Banquillo", 
    "Player 1 Deck 2": "Jugador 1 Mazo 2", 
    "Player 1 Play Area 1": "Jugador 1 Zona de juego 1",
    "Player 1 Play Area 2": "Jugador 1 Zona de juego 2", 
    "Player 1 Play Area 3": "Jugador 1 Zona de juego 3", 
    "Player 1 Play Area 4": "Jugador 1 Zona de juego 4", 
    "Player 1 Engaged Area": "Jugador 1 Zona de enfrentamiento", 
    "Player 1 Current Event": "Jugador 1 Evento actual", 
    "Player 2 Hand": "Jugador 2 Mano", 
    "Player 2 Deck": "Jugador 2 Mazo", 
    "Player 2 Discard": "Jugador 2 Descartes", 
    "Player 2 Sideboard": "Jugador 2 Banquillo", 
    "Player 2 Deck 2": "Jugador 2 Mazo 2", 
    "Player 2 Play Area 1": "Jugador 2 Zona de juego 1",
    "Player 2 Play Area 2": "Jugador 2 Zona de juego 2", 
    "Player 2 Play Area 3": "Jugador 2 Zona de juego 3", 
    "Player 2 Play Area 4": "Jugador 2 Zona de juego 4", 
    "Player 2 Engaged Area": "Jugador 2 Zona de enfrentamiento", 
    "Player 2 Current Event": "Jugador 2 Evento actual", 
    "Player 3 Hand": "Jugador 3 Mano", 
    "Player 3 Deck": "Jugador 3 Mazo", 
    "Player 3 Discard": "Jugador 3 Descartes", 
    "Player 3 Sideboard": "Jugador 3 Banquillo", 
    "Player 3 Deck 2": "Jugador 3 Mazo 2", 
    "Player 3 Play Area 1": "Jugador 3 Zona de juego 1",
    "Player 3 Play Area 2": "Jugador 3 Zona de juego 2", 
    "Player 3 Play Area 3": "Jugador 3 Zona de juego 3", 
    "Player 3 Play Area 4": "Jugador 3 Zona de juego 4", 
    "Player 3 Engaged Area": "Jugador 3 Zona de enfrentamiento", 
    "Player 3 Current Event": "Jugador 3 Evento actual", 
    "Player 4 Hand": "Jugador 4 Mano", 
    "Player 4 Deck": "Jugador 4 Mazo", 
    "Player 4 Discard": "Jugador 4 Descartes", 
    "Player 4 Sideboard": "Jugador 4 Banquillo", 
    "Player 4 Deck 2": "Jugador 4 Mazo 2", 
    "Player 4 Play Area 1": "Jugador 4 Zona de juego 1",
    "Player 4 Play Area 2": "Jugador 4 Zona de juego 2", 
    "Player 4 Play Area 3": "Jugador 4 Zona de juego 3", 
    "Player 4 Play Area 4": "Jugador 4 Zona de juego 4", 
    "Player 4 Engaged Area": "Jugador 4 Zona de enfrentamiento", 
    "Player 4 Current Event": "Jugador 4 Evento actual", 
    "Event": "Evento",
    "Round": "Ronda",
    "Staging": "Amenaza",
    "Progress": "Progreso",
    "Get up": "Levantarse",
    "Look": "Mirar",
    "Sit down": "Sentarse",
    "Taken": "Tomado",
    "Shuffle": "Barajar",
    "Browse": "Buscar",
    "Look at top 5": "Mirar las 5 superiores",
    "Look at top 10": "Mirar las 10 superiores",
    "Look at top X": "Mirar las X superiores",
    "Choose random": "Elegir aleatoriamente",
    "Move to": "Mover a",
    "More": "Más",
    "Deal top X facedown": "Repartir las X superiores boca abajo",
    "Flip": "Voltear",
    "Exhaust": "Agotar",
    "Prevent refresh": "Evitar recuperación",
    "Delete": "Borrar",
    "Per round": "Por ronda",
    "Toggle triggers": "Activadores",
    "Top": "Superior",
    "Shuffle in": "Barajar en",
    "Shuffle into top X": "Barajar X superiores en",
    "Shuffle into bottom X": "Barajar X inferiores en",
    "Bottom": "Inferior",
    "New Round": "Nueva ronda",
    "Peek": "Ojear",
    "Swap with top": "Intercambiar con la superior",
    "Make visible/hidden": "Hacer visible/ocultar",
    "resource": "Recurso",
    "progress": "Progreso",
    "damage": "Daño",
    "time": "Tiempo",
    "willpower": "Fuerza de Voluntad",
    "attack": "Ataque",
    "defense": "Defensa",
    "threat": "Amenaza",
    "hitPoints": "Puntos de Impacto",
    "Standard": "Estándar",
    "Extra staging areas / map": "Áreas de preparación extra / mapa",
    "Beginning": "Comienzo",
    "Resource": "Recurso",
    "Set first player": "Establecer jugador inicial",
    "0.0": "Comienzo de la ronda",
    "1.1": "Comienzo de la Fase de Recursos",
    "1.R": "1.2 & 1.3: Obtener recursos y robar cartas - <u>ventana de acción</u>",
    "1.4": "Fin de la Fase de Recursos",  
    "Planning": "Planificación",
    "2.1": "Comienzo de la Fase de Planificación",
    "2.P": "2.2 & 2.3: Jugar cartas en orden de turno - <u>ventana de acción</u>",
    "2.4": "Fin de la Fase de Planificación",
    "Quest": "Misión",
    "3.1": "Comienzo de la Fase de Misión - <u>ventana de acción</u>",
    "3.2": "Asignar personajes a la misión - <u>ventana de acción</u>",
    "3.3": "Preparación - <u>ventana de acción</u>",
    "3.4": "Resolución de la misión - <u>ventana de acción</u>",
    "3.5": "Fin de la Fase de Misión",
    "Travel": "Viaje",
    "4.1": "Comienzo de la Fase de Viaje",
    "4.2": "Opción de viaje - <u>ventana de acción</u>",
    "4.3": "Fin de la Fase de Viaje",
    "Encounter": "Encuentros",
    "5.1": "Comienzo de la Fase de Encuentros",
    "5.2": "Enfrentamientos opcionales - <u>ventana de acción</u>",
    "5.3": "Comprobaciones de enfrentamiento - <u>ventana de acción</u>",
    "5.4": "Fin de la Fase de Encuentros",
    "Combat": "Combate",
    "6.1": "Comienzo de la Fase de Combate",
    "6.2": "Repartir cartas de Sombra",
    "6.E": "Resolver ataques enemigos - <u>ventana de acción tras cada paso de combate</u>",
    "6.P": "Ataques del jugador - <u>ventana de acción tras cada paso de combate</u>",
    "6.11": "Fin de la Fase de Combate",
    "Refresh": "Recuperación",
    "7.1": "Comienzo de la Fase de Recuperación",
    "7.R": "Preparar cartas, aumentar amenaza, pasar la ficha de jugador inicial - <u>ventana de acción</u>",
    "7.5": "Fin de la Fase de Recuperación",
    "End": "End",
    "Go Back": "Regresa",
    "Detach": "Despegar",
    "Swap side": "Cambiar de lado",
    "Stop peeking": "Deja de espiar",
    "Keep order": "Mantén el orden",
    "Keep peeking": "Sigue espiando",
    "Enemy": "Enemigo",
    "Location": "Lugar",
    "Treachery": "Traición",
    "All": "Todas",
    "Ally": "Aliado",
    "Attachment": "Vinculada",
    "Event": "Evento",
    "Other": "Otra",
    "Easy": "Fácil",
    "Normal": "Normal",
    "Nightmare": "Pesadilla",
    "None": "Ninguna",
    "Top 5": "5 superiores",
    "Top 10": "10 superiores",
    "Turn faceup...": "Poner boca arriba...",
    "Close &": "Cerrar &",
  },
  "French": {
  },
}